### ISSUE TITLE
Is this repo required for running BO4 client independent from Treyarch's servers in today's state?

### ISSUE THREAD

**Issue by jumofogit** [project-bo4/shield-development#2]

**Comment by project-bo4** [comment]
greeting. unfortunately didnt quite understand what you mean but in a general explanation:
This is client-side hook aka detour and in first place it has 

server is currently being worked on by one of our team members assigned to dw emulation. but because of extreme protections used by treyarch it is very time consuming and frustrating and needs some time before getting to ultimate flawless state

And yes its planned to be in-dependent from official servers as they proven to be extremely in-consistent these days. some minor policies may be subject to change tho.

finally i should remind you to consider it is first time call of duty receiving external modification since it moved on to battlenet so you should give it some time before judging it performance

**Comment by jumofogit** [comment]
well, can game run now without having a license or Battle.net running on bg?

**Comment by jumofogit** [comment]
oh, wait, I tried to compile it
it is trying to connect to somewhere
![Снимок экрана (203)](https://user-images.githubusercontent.com/116519368/223769043-1b0e5741-d2ae-4b5f-9b12-35072fa35066.png)

**Comment by jumofogit** [comment]
oh, well, I tried force connections go to localhost, there is black screen
anyway, there is any working version of game with this client? to at least run it after screen on screenshot, maybe.

**Comment by project-bo4** [comment]
Yes earlier builds work fine mainly because at time, anti-tampering logics were not as strict as newer builds. but i doubt you would get access to any of them since bnet does not have depot cdn. 

btw i will conduct play tests soon to research cause of in-consistency with help of players; this will including online functionalities those are re-created as of right now. we going to setup a discord server to get contact. wait for announcement on twitter.
