### ISSUE TITLE
Aim assist 

### ISSUE THREAD

**Issue by hcwd** [project-bo4/shield-development#8]
Hi, is it possible for you to add aim assist to the client

**Comment by project-bo4** [comment]
greetings. we have already done a research and managed to get it working. only hipfire target-assist is presented on pc and its disabled by default but it can be toggled using its variable.

for setting variables we need to make a spoofed-call helper(because variables are protected by anticheat we cant modify them directly) ... we already considering it as our todo priorities and we will be on at soon as we get chance.

p.s: we already have a spoofed-call library in our developer build but since it used MASM we didnt include it as it would make compiling for casual users way more complicated.

**Comment by hcwd** [comment]
Could you provide the files needed for compiling it?

**Comment by haydencarlson** [comment]
Actually so exciting if you get aim assist fully working :clap:
